spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/witspirit/spring-config-experiments.git
          search-paths: config-data/
          basedir: target/config-clone
