spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/witspirit/spring-config-experiments.git
          search-paths: config-data/
          basedir: target/config-clone
          repos:
            config-client:
              pattern: config-client
              uri: https://github.com/witspirit/config-client-config-repo.git


# A non default port to differentiate for the normal 8888 config server port and the 8080 boot app port
server:
  port: 8088